import os

BASE_URL = "https://bill.pitc.com.pk"
SEARCH_URL = f"{BASE_URL}/iescobill"

REFERENCE_COLUMN = "reference_no"

MAX_WORKERS = 5
REQUEST_DELAY = 0.30
MAX_REFERENCES = 200

CONNECT_TIMEOUT = 30
READ_TIMEOUT = 45

PROXY_URL = os.getenv("PROXY_URL")  # e.g. socks5://100.87.17.94:1080

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/150.0.0.0 Safari/537.36"
    ),
    "Referer": SEARCH_URL,
}

REFERENCE_KEY_CANDIDATES = [
    "REFERENCE_NO",
    "REFERENCE_NUMBER",
    "REF_NO",
    "REF_NUMBER",
    "CONSUMER_REFERENCE_NO",
    "CONSUMER_REFERENCE_NUMBER",
    "CONSUMER_DETAILS_REFERENCE_NO",
    "CONSUMER_DETAILS_REFERENCE_NUMBER",
    "CUSTOMER_DETAILS_REFERENCE_NO",
    "CUSTOMER_DETAILS_REFERENCE_NUMBER",
]

WEBSITE_PAYABLE_KEY_CANDIDATES = [
    "PAYABLE_WITHIN_DUE_DATE",
    "AMOUNT_PAYABLE_WITHIN_DUE_DATE",
    "TOTAL_PAYABLE_WITHIN_DUE_DATE",
    "PAYABLE_DUE_DATE",
    "AMOUNT_WITHIN_DUE_DATE",
    "BILL_AMOUNT_WITHIN_DUE_DATE",
    "CURRENT_BILL_PAYABLE_WITHIN_DUE_DATE",
    "PAYABLE_WITHIN_DUE_DATE_TOTAL",
]
